'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api';
import { MINISTRY_PARTS } from '@/lib/options';

interface Team { id: string; name: string; description: string | null; leaderProfile: { preferredParts: string[]; customPart: string | null }; }
export default function TeamDirectoryPage() {
  const [teams, setTeams] = useState<Team[]>([]); const [selected, setSelected] = useState<Team | null>(null); const [excludedParts, setExcludedParts] = useState<string[]>([]); const [date, setDate] = useState(''); const [location, setLocation] = useState(''); const [pay, setPay] = useState(''); const [message, setMessage] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { apiFetch<Team[]>('/teams').then(setTeams).catch((error) => setNotice(error instanceof Error ? error.message : '팀을 불러오지 못했습니다.')); }, []);
  const toggle = (part: string) => setExcludedParts((current) => current.includes(part) ? current.filter((item) => item !== part) : [...current, part]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!selected) return; try { await apiFetch(`/proposals/teams/${selected.id}`, { method: 'POST', body: JSON.stringify({ proposedDate: date || undefined, location: location || undefined, compensationAmount: pay ? Number(pay) : undefined, excludedParts, message }) }); setNotice('팀 대표에게 제안을 보냈습니다.'); setSelected(null); } catch (error) { setNotice(error instanceof Error ? error.message : '제안에 실패했습니다.'); } }
  return <main className="bg-slate-50 px-4 py-7"><div className="mx-auto max-w-5xl"><div className="flex items-end justify-between"><div><p className="text-sm font-bold text-violet-600">TEAM DIRECTORY</p><h1 className="mt-1 text-3xl font-extrabold">팀 사역자 찾기</h1><p className="mt-2 text-sm text-slate-500">팀 전체에 제안하되 필요 없는 파트는 제외할 수 있습니다.</p></div><Link href="/ministers" className="text-sm font-bold text-[#1463FF]">개인 사역자 보기</Link></div><div className="mt-6 grid gap-4 md:grid-cols-2">{teams.map((team) => <article key={team.id} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-violet-600">TEAM</p><h2 className="mt-1 text-xl font-extrabold text-slate-900">{team.name}</h2><p className="mt-2 text-sm text-slate-600">{team.description || '팀 소개가 없습니다.'}</p><p className="mt-4 text-sm text-slate-500">대표 파트: {[...team.leaderProfile.preferredParts, team.leaderProfile.customPart].filter(Boolean).join(' · ')}</p><button onClick={() => setSelected(team)} className="mt-5 rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">팀에게 제안</button></article>)}</div>{selected && <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-6"><h2 className="text-xl font-extrabold">{selected.name}에게 제안</h2><label className="mt-4 block text-sm font-bold">제안 일자<input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2" /></label><label className="mt-3 block text-sm font-bold">장소<input value={location} onChange={(e) => setLocation(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2" /></label><label className="mt-3 block text-sm font-bold">제안 페이<input type="number" value={pay} onChange={(e) => setPay(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2" /></label><fieldset className="mt-4"><legend className="text-sm font-bold">제외할 파트</legend><div className="mt-2 flex flex-wrap gap-2">{MINISTRY_PARTS.map((part) => <button type="button" key={part} onClick={() => toggle(part)} className={`rounded-full px-3 py-1 text-xs font-bold ${excludedParts.includes(part) ? 'bg-red-100 text-red-700' : 'bg-slate-100 text-slate-600'}`}>{excludedParts.includes(part) ? `${part} 제외` : part}</button>)}</div></fieldset><label className="mt-4 block text-sm font-bold">메시지<textarea required minLength={10} value={message} onChange={(e) => setMessage(e.target.value)} rows={4} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2" /></label><div className="mt-5 flex gap-2"><button type="button" onClick={() => setSelected(null)} className="flex-1 rounded-xl bg-slate-100 py-2.5 text-sm font-bold">취소</button><button className="flex-1 rounded-xl bg-[#1463FF] py-2.5 text-sm font-bold text-white">제안 보내기</button></div></form></div>}{notice && <p className="mt-5 text-sm font-bold text-blue-700">{notice}</p>}</div></main>;
}
