'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { apiFetch } from '@/lib/api';

type Role = 'MINISTER' | 'CHURCH_ADMIN';

export default function SignupPage() {
  const router = useRouter(); const [role, setRole] = useState<Role>('MINISTER'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [phone, setPhone] = useState(''); const [isPhonePublic, setIsPhonePublic] = useState(false); const [error, setError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); setIsSubmitting(true); try { await apiFetch('/users', { method: 'POST', body: JSON.stringify({ email, password, role, ...(phone ? { phone, isPhonePublic } : {}) }) }); router.push('/login?registered=1'); } catch (err) { setError(err instanceof Error ? err.message : '회원가입에 실패했습니다.'); } finally { setIsSubmitting(false); } }
  return <main className="flex flex-1 justify-center bg-slate-50 px-4 py-10"><form onSubmit={submit} className="w-full max-w-md rounded-xl bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold text-[#1E3A5F]">회원가입</h1><p className="mt-2 text-sm text-slate-500">어떤 방식으로 서비스를 이용하시나요?</p><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={() => setRole('MINISTER')} className={`rounded-lg border p-3 text-sm font-medium ${role === 'MINISTER' ? 'border-[#1E3A5F] bg-blue-50 text-[#1E3A5F]' : 'border-slate-200'}`}>사역자</button><button type="button" onClick={() => setRole('CHURCH_ADMIN')} className={`rounded-lg border p-3 text-sm font-medium ${role === 'CHURCH_ADMIN' ? 'border-[#1E3A5F] bg-blue-50 text-[#1E3A5F]' : 'border-slate-200'}`}>교회 담당자</button></div><label className="mt-5 block text-sm font-medium text-slate-700">이메일<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="mt-4 block text-sm font-medium text-slate-700">비밀번호<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /><span className="mt-1 block text-xs font-normal text-slate-500">8자 이상 입력해 주세요.</span></label><label className="mt-4 block text-sm font-medium text-slate-700">휴대전화 <span className="font-normal text-slate-400">(선택)</span><input type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="010-1234-5678" className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="mt-3 flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={isPhonePublic} disabled={!phone} onChange={(e) => setIsPhonePublic(e.target.checked)} />매칭 확정 상대에게 휴대전화 공개</label>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<button disabled={isSubmitting} className="mt-6 w-full rounded-md bg-[#1E3A5F] py-2.5 font-medium text-white disabled:opacity-50">{isSubmitting ? '가입 중…' : '가입하기'}</button><p className="mt-5 text-center text-sm text-slate-500">이미 계정이 있나요? <Link href="/login" className="font-medium text-[#1E3A5F]">로그인</Link></p></form></main>;
}
