'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { apiFetch } from '@/lib/api';

interface Activity { id: string; status?: string; posting?: { id: string; location: string; serviceDate: string }; location?: string; serviceDate?: string; }
interface Proposal { id: string; proposedDate: string | null; location: string | null; compensationAmount: number | null; message: string; churchProfile?: { churchName: string }; ministerProfile?: { preferredParts: string[] }; }

export default function DashboardPage() {
  const { user, isLoading } = useAuth(); const [activities, setActivities] = useState<Activity[]>([]); const [proposals, setProposals] = useState<Proposal[]>([]); const [error, setError] = useState('');
  useEffect(() => { if (!user) return; const path = user.role === 'MINISTER' ? '/applications/me' : '/postings/me'; apiFetch<Activity[]>(path).then(setActivities).catch((err) => setError(err instanceof Error ? err.message : '활동을 불러오지 못했습니다.')); apiFetch<Proposal[]>('/proposals/me').then(setProposals).catch(() => undefined); }, [user]);
  if (isLoading) return <main className="p-10 text-center">불러오는 중…</main>; if (!user) return <main className="p-10 text-center">로그인 후 이용해 주세요.</main>;
  const isMinister = user.role === 'MINISTER';
  return <main className="bg-slate-50 px-4 py-7"><div className="mx-auto max-w-4xl"><div className="flex items-center justify-between"><div><p className={`text-sm font-bold ${isMinister ? 'text-blue-600' : 'text-violet-600'}`}>{isMinister ? '사역자 모드' : '모집자 모드'}</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">내 활동</h1></div><Link href={isMinister ? '/postings' : '/ministers'} className="rounded-xl bg-[#1463FF] px-4 py-2.5 text-sm font-bold text-white">{isMinister ? '사역 찾기' : '사역자 찾기'}</Link></div>{error && <p className="mt-5 text-sm text-red-600">{error}</p>}<section className="mt-6"><h2 className="text-lg font-extrabold text-slate-900">{isMinister ? '받은 제안' : '보낸 제안'}</h2>{proposals.length === 0 ? <p className="mt-3 rounded-2xl bg-white p-5 text-sm text-slate-500">아직 제안이 없습니다.</p> : <div className="mt-3 grid gap-3">{proposals.map((proposal) => <article key={proposal.id} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm font-bold text-[#1463FF]">{isMinister ? proposal.churchProfile?.churchName : proposal.ministerProfile?.preferredParts.join(' · ')}</p><p className="mt-2 text-sm text-slate-600">{proposal.proposedDate && `${new Date(proposal.proposedDate).toLocaleDateString('ko-KR')} · `}{proposal.location}</p>{proposal.compensationAmount && <p className="mt-2 text-sm font-extrabold text-[#1463FF]">제안 페이 {proposal.compensationAmount.toLocaleString()}원</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{proposal.message}</p></article>)}</div>}</section><section className="mt-8"><h2 className="text-lg font-extrabold text-slate-900">{isMinister ? '내 지원' : '내 공고'}</h2>{activities.length === 0 ? <p className="mt-3 rounded-2xl bg-white p-5 text-sm text-slate-500">아직 활동 내역이 없습니다.</p> : <div className="mt-3 grid gap-3">{activities.map((item) => { const posting = item.posting; return <Link key={item.id} href={`/postings/${posting?.id ?? item.id}`} className="rounded-2xl bg-white p-5 shadow-sm"><p className="font-bold text-slate-900">{posting?.location ?? item.location}</p><p className="mt-1 text-sm text-slate-500">{new Date(posting?.serviceDate ?? item.serviceDate ?? '').toLocaleDateString('ko-KR')}{item.status && ` · ${item.status}`}</p></Link>; })}</div>}</section></div></main>;
}
